### ISSUE TITLE
Output Labels alphabetically

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#10]
Hey, I looked at the API briefly and didn't notice an order call for the labels. Is there a way you could output these alphabetically before it gets called on the page-label.php partial?

**Comment by purduekenny** [comment]
Also, there's a comment in there about passing the home so they stay on site - that would be good to implement as well. Should I make another issue or can you take it from this one?

**Comment by sfp-john** [comment]
Think I got them both knocked out.  Tests working well for /benton/label/7

https://github.com/PurdueAgComm/Extension-2018/commit/79627b9c3872e804cc7a515ac26e11221630a3a5

**Comment by purduekenny** [comment]
yup merged and fixed conflicts and it looks like it's working well, thanks for the fast turn around john
