### ISSUE TITLE
County name in header/footer files

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#12]
Could you create a function that gets the county name if I'm on /county/ so I can use it in any /partials/ file? 

For example, currently extension.purdue.edu/benton, Benton County is in the header of the site. I'll probably need to implement something like that.

**Comment by sfp-john** [comment]
There is a function get_county_name() you can call, I believe from any file or partial, to return the current county that is being used.  It'll return "Extension" if no county is detected in the current page path/url.  Let me know if this meets your needs.

**Comment by sfp-nathan** [comment]
This looks like it's done.  I'll be sure to test it before closing out this issue.
