### ISSUE TITLE
about page API: hours available?

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#14]
In the current var_dump I don't see any hours available. My contact is saying that they vary with the government hours. Ex: 

https://extension.purdue.edu/Kosciusko/Pages/aboutus.aspx
https://extension.purdue.edu/Morgan/Pages/aboutus.aspx

Thoughts?

**Comment by sfp-john** [comment]
I'm searching through the available API calls to see if I can track this data down.

**Comment by sfp-nathan** [comment]
I've searched high and low through the API calls to try to find operational hours, but haven't found anything.  It doesn't appear the API supports this functionality, or if it does, it's escaped inclusion in the documentation.

**Comment by purduekenny** [comment]
I'll follow up with the unit that created the API. Thanks Nathan.
