### ISSUE TITLE
Navigating to /benton/ doesn't use /pages/county.php but uses /pages/home.php

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#3]
I've added in different functions based on home and county homepages but it seems as if /benton/ calls up home.php instead of county.php. It does pull the correct data, though.

**Comment by sfp-john** [comment]
Added some logic to check if we're looking at the main homepath (ID=1) or a county specified and switch the template on that "root"

https://github.com/PurdueAgComm/Extension-2018/commit/e4f948f588545016f78f33b605b6204cbb33ec2a

**Comment by purduekenny** [comment]
This looks to be working fantastically, thanks!
