### ISSUE TITLE
get_category_name() function

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#6]
get_category_lists gets the articles within a specified category; however, there's no API hook that I see that gets the name of the category for a passed ID. I will use this on category pages as a heading before I output get_category_lists.

**Comment by sfp-john** [comment]
get_category_name now functions by gathering the friendly name from the menu API call.

https://github.com/PurdueAgComm/Extension-2018/commit/a04c08a98962c197b578167f352ed6598c0ca10e
