### ISSUE TITLE
On Event Detail page, /{inteventID}/{intEventDateID/ needs to be able to be passed and on event list page, list the intEventDateID instead of only the eventID

### ISSUE THREAD

**Issue by purduekenny** [PurdueAgComm/Extension-2018#9]
Hey, I need to be able to specify intEventDateID on the event list page so that when someone clicks a specific dateTime for an event (that could have multiple) they go to the event detail page with a that date, time, and location first.

Let me know if that makes sense, we can talk it through if not.

**Comment by sfp-john** [comment]
Okay, makes sense.

I've pulled fresh, working on this item now.

**Comment by sfp-john** [comment]
I'm going to introduce a new template partial for the full event list/filter page.  The calls are different from the homepage list.  I don't want to introduce too much logic or switching into the feed-event.php template if it's working well for the homepage already.

**Comment by sfp-john** [comment]
The call isn't documented to specify event ID, going to see if I can dig this out by educated guess.

**Comment by sfp-john** [comment]
Okay, merged up, check out this commit: https://github.com/PurdueAgComm/Extension-2018/commit/759a48939ae6fb436cf6f4bbf870eb8550d6d3e1

Event Date is now a mandatory part of the path, much like the current site, for event details.  We could try and dance around allowing both and listing the first event date, but that could add unnecessary complexity.

I didn't want to modify page-even.php too much, so I've got a var_dump at the top showing the matching of the date to the linked event date allowing the template to echo out the details for that specific event date.

**Comment by purduekenny** [comment]
Hey John, I'll need some more time to dig into this one before I can verify everything. Tomorrow afternoon and Friday are open so I should get back to you then with updates.

**Comment by purduekenny** [comment]
With your updates, event-page.php is showing NULL for both the `var_dump($event)` and `var_dump($eventDate)` 

I checked out the event-list.php and didn't see why this would be. Is it working on your machine?

**Comment by sfp-john** [comment]
Ah, yeah try adding the event ID to the path.  I've updated the links in the event feed list to include that.  The current site passes it along every time, even for single day events, so I hope it's okay to make it mandatory as part of the path:

![image](https://user-images.githubusercontent.com/38105458/39877398-e106ba72-5443-11e8-8b5c-8cc6371419ab.png)


Example path: /event/21088/34728

**Comment by sfp-john** [comment]
If not, I could try writing the path logic to accept both scenarios, and if the event date id is missing, just show the first date by default.

**Comment by purduekenny** [comment]
Lines 45-48 of feed-event.php have 

`<?php if($eventED): ?>
    <a class="events--link" href="/event/<?php echo $event->intEventID; ?>/<?php echo $eventED;?>">
    <?php else: ?>
    <a class="events--link" href="/event/<?php echo $event->intEventID; ?>">
    <?php endif; ?>`

Which seems to assert that an event date ID isn't needed. Should this be reworked? 

I think it would be best to allow to accept only event ID and default to the next date, how much work would that be?

**Comment by sfp-john** [comment]
Okay, think I got something workable here:

https://github.com/PurdueAgComm/Extension-2018/commit/3b930a074792612c05872168eb11840daa8dc07d

This makes the path optional, if present and multiday, it'll have those details available for replacement into the template vars.
